name: testetcc
description: Aplicativo de análise de tráfego urbano usando teoria dos grafos

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Google Maps
  google_maps_flutter: 2.2.5
  
  # Localização - versões compatíveis
  geolocator: ^11.1.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true