// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKsWNoWnVGvYZkPC_gAffmc3QK13b_czQ',
    appId: '1:944159939869:web:0d666c6bfa83054d6215f4',
    messagingSenderId: '944159939869',
    projectId: 'tcc-transito-colatina',
    authDomain: 'tcc-transito-colatina.firebaseapp.com',
    storageBucket: 'tcc-transito-colatina.firebasestorage.app',
    measurementId: 'G-NB11Y45BK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOX9_xx2JdOOy7iMUynQNxurG1B6FFYis',
    appId: '1:944159939869:android:9f1d41ad29a54e256215f4',
    messagingSenderId: '944159939869',
    projectId: 'tcc-transito-colatina',
    storageBucket: 'tcc-transito-colatina.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoGlCfc0PLMIqY1iSXG6cCv7yVfAmUV6A',
    appId: '1:944159939869:ios:79e6a2f839a330236215f4',
    messagingSenderId: '944159939869',
    projectId: 'tcc-transito-colatina',
    storageBucket: 'tcc-transito-colatina.firebasestorage.app',
    iosBundleId: 'com.example.testetcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoGlCfc0PLMIqY1iSXG6cCv7yVfAmUV6A',
    appId: '1:944159939869:ios:79e6a2f839a330236215f4',
    messagingSenderId: '944159939869',
    projectId: 'tcc-transito-colatina',
    storageBucket: 'tcc-transito-colatina.firebasestorage.app',
    iosBundleId: 'com.example.testetcc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKsWNoWnVGvYZkPC_gAffmc3QK13b_czQ',
    appId: '1:944159939869:web:382111f5a08aa19c6215f4',
    messagingSenderId: '944159939869',
    projectId: 'tcc-transito-colatina',
    authDomain: 'tcc-transito-colatina.firebaseapp.com',
    storageBucket: 'tcc-transito-colatina.firebasestorage.app',
    measurementId: 'G-9CRYDVM7XS',
  );
}
